/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.checkerframework.checker.units.qual.A;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void TestsFile() {
        try {
            BufferedReader dataJson = new BufferedReader(new FileReader("C:\\Users\\WAEL\\quotes\\data.json"));
            Gson gson = new Gson();

            wisdom[] dataJavaOpject= gson.fromJson(dataJson, wisdom[].class);


           assertEquals(dataJavaOpject[1].toString(),"'Ask no questions, and you'll be told no lies.'    author:'Charles Dickens'");
        }
        catch (IOException ex) {
            ex.printStackTrace();
            System.out.println("CANT FIND");


        }

    }



    @Test void TestsApi() throws IOException {
        App API=new App();



        assertEquals(API.APIQuteReader(),API.APIQuteReader());


    }
}
