/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void Tests() {
        try {
            BufferedReader dataJson = new BufferedReader(new FileReader("C:\\Users\\WAEL\\quotes\\data.json"));
            Gson gson = new Gson();

            wisdom[] dataJavaOpject= gson.fromJson(dataJson, wisdom[].class);
            int random1 = (int) (Math.random()*100);
            int random2 = (int) (Math.random()*100);
           assertNotEquals(dataJavaOpject[random1].toString(),dataJavaOpject[random2].toString());

        }
        catch (IOException ex) {
            ex.printStackTrace();
            System.out.println("CANT FIND");


        }

    }
}
