/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws FileNotFoundException {


           try {
               BufferedReader dataJson = new BufferedReader(new FileReader("C:\\Users\\WAEL\\quotes\\data.json"));
               Gson gson = new Gson();

               wisdom[] dataJavaOpject= gson.fromJson(dataJson, wisdom[].class);
               int random = (int) (Math.random()*100);
               System.out.println( dataJavaOpject[random].toString());

           }
           catch (IOException ex) {
               ex.printStackTrace();

            }

    }
}
