/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;

import java.net.URL;
import com.google.gson.Gson;

import java.io.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {

        APIQuteReader();


    }




    public static String FileQuteReader() throws IOException {
        try {
            System.out.println("................REad from json file.....................");
            BufferedReader dataJson = new BufferedReader(new FileReader("C:\\Users\\WAEL\\quotes\\data.json")); // read from file
            Gson gson = new Gson();// json library

            wisdom[] dataJavaOpject= gson.fromJson(dataJson, wisdom[].class); // convert from json using class i created and  library
            int random = (int) (Math.random()*100);
            System.out.println( dataJavaOpject[random].toString());
return dataJavaOpject[random].toString();
        }
        catch (IOException ex) {
            ex.printStackTrace();

        }
        return  "nodata";
    }





    public static String APIQuteReader() throws IOException {
        URL quoteApiUrl = null; //url of api
        try {

            quoteApiUrl = new URL("http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en");//URL OF API
            HttpURLConnection ApiConnection = (HttpURLConnection) quoteApiUrl.openConnection();// connection to api

            ApiConnection.setRequestMethod("GET");// mecthode o request

            InputStreamReader streamReader = new InputStreamReader(ApiConnection.getInputStream());// TO READ RESPONSE
            BufferedReader ApiBuffer=new BufferedReader(streamReader);// to store the response in  buffer
            String ApiJson=ApiBuffer.readLine();//to read buffer
            // System.out.println(ApiJson);
            Gson gson=new Gson();//library to deal with json
            ApiQute qute=gson.fromJson(ApiJson,ApiQute.class); //to convert to java object using Api class that i created
            System.out.println(".....................................");
            System.out.println(qute);

            File dittoFile = new File("./ditto.json");// to create new file
            try (FileWriter dittoFileWriter = new FileWriter(dittoFile)) { // to write on it
                gson.toJson(qute, dittoFileWriter);// to write the response on it
            }

            return  qute.toString();

        }

        catch (IOException e) {// to read from file in case the internet  was disconnect
            try {
                BufferedReader dataJson = new BufferedReader(new FileReader("C:\\Users\\WAEL\\quotes\\ditto.json")); // read from file
                if (dataJson.readLine()== null) //if file empty (in case you run the programe in the first time and the internet disconnect)
                {
                    System.out.println(dataJson);
                    return FileQuteReader();
                }
               else {

                    Gson gson = new Gson();//library to deal with json

                    ApiQute qute = gson.fromJson(dataJson, ApiQute.class); //to convert to java object using Api class that i created
                    System.out.println("-------------FROM  Response FILE---------------");// to indecate that i use file
                    System.out.println(qute.toString());// to print the qute from file
                    return qute.toString();
                }
            }
            catch (Exception exception){


        }

        }

return "no data";

    }



}
